apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: harbor-kustomize
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: aws-platform-prod-observability-001
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-harbor'
      labels:
        app: "harbor-kustomize"
        environment: 'prod'
    spec:
      project: default
      syncPolicy:
        # Disable auto-sync
        # automated: {}
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/dchai94/argocd-app-config.git
        path: project/harbor_kustomize/harbor/overlays
        targetRevision: HEAD
        plugin:
          name: kustomize-enable-helm
      destination:
        server: '{{url}}'
        namespace: harbor 
