apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patches:
- path: patches/ingress.yaml
- path: patches/harbor-portal-cm.yaml
# - target:
#     kind: Ingress
#     name: harbor-ingress
#   patch: |-
#     - op: remove
#       path: /spec/tls