apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patches:
- path: patches/ingress.yaml
- path: patches/harbor-portal-cm.yaml
# - target:
#     kind: Ingress
#     name: harbor-ingress
#   patch: |-
#     - op: remove
#       path: /spec/tls
# - target:
#     kind: Deployment
#     name: harbor-jobservice
#   patch: |-
#     - op: replace
#       path: /spec/strategy/type
#       value: Recreate
#     - op: replace
#       path: /spec/template/spec/containers/0/image
#       value: test0
    
# - target:
#     kind: Deployment
#     name: harbor-registry
#   patch: |-
#     - op: replace
#       path: /spec/strategy/type
#       value: Recreate
#     - op: replace
#       path: /spec/template/spec/containers/0/image
#       value: test0
#     - op: replace
#       path: /spec/template/spec/containers/1/image
#       value: test1
- target:
    kind: Deployment
    name: harbor-registry     
  patch: |-
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "iam-key-aws-secrets"
    # - op: add
    #   path: /spec/template/spec/containers/0/volumeMounts
    #   value: 
    #     name: secrets-store-inline
    #     mountPath: "/mnt/secrets-store"
    #     readOnly: true
