apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patches:
- path: patches/ingress.yaml
- target:
    kind: Ingress
    name: harbor-ingress
  patch: |-
    - op: delete
      path: /spec/tls