apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: karpenter
spec:
  project: default
  source:
    repoURL: https://gitlab.com/dchai94/argocd-app-config.git
    targetRevision: HEAD
    path: karpenter
    #chart: karpenter
    helm:
	releaseName: karpenter
  destination: 
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
