apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dchai94/argocd-app-config.git
    #repoURL: 'https://github.com/tanmay-bhat/podinfo'
    #path: charts/podinfo
    targetRevision: HEAD
    path: karpenter
    #chart: karpenter
    helm:
       releaseName: karpenter
       valueFiles:
       #- test.yaml
       - values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
