apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dchai94/argocd-app-config.git
    #repoURL: 'https://github.com/tanmay-bhat/podinfo'
    #path: charts/podinfo
    targetRevision: HEAD
    path: project/harbor/harbor
    #chart: karpenter
    helm:
       releaseName: karpenter
       valueFiles:
       - ../values.yaml
       #- values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
