apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: signoz
  includeCRDs: true
  namespace: signoz
  releaseName: signoz
  version: 0.27.1
  repo: https://charts.signoz.io
  valuesInline:
    frontend:
      ingress:
        enabled: true
        className: "nginx"
