apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: secrets-store-csi-driver
  includeCRDs: true
  namespace: kube-system
  releaseName: secrets-store-csi-driver
  version: 1.3.0
  repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  valuesInline:
    syncSecret:
      enabled: true
    enableSecretRotation: true