apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#resources:
# - aws-provider-installer.yaml
#- secret-provider-class.yaml

helmCharts:
- name: secrets-store-csi-driver
  includeCRDs: true
  namespace: kube-system
  releaseName: csi-secrets-store
  version: 1.3.0
  repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  valuesInline:
    syncSecret:
      enabled: true
    enableSecretRotation: true