apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: iam-key-aws-secrets
  namespace: harbor
spec:
  provider: aws
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: foosecret
    type: Opaque
    labels:
      environment: "test"
    data:
    - objectName: "prod/test/test"                 # name of the mounted content to sync. this could be the object name or object alias
      key: username
  parameters:
    objects: |
        - objectName: "prod/test/test"
          objectType: "secretsmanager"