apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: iam-key-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "prod/test/test"
          objectType: "secretsmanager"