apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-store-csi-driver-provider-aws
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: aws-sg-platform-prod-eks-observability-002
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'secrets-store-csi-driver-provider-aws'
      labels:
        app: "secrets-store-csi-driver-provider-aws"
        environment: 'prod'
    spec:
      project: default
      syncPolicy:
        # Disable auto-sync
        # automated: {}
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/dchai94/argocd-app-config.git
        path: project/secrets-store-csi-driver-provider-aws/secrets-store-csi-driver-provider-aws/overlays
        targetRevision: HEAD
        plugin:
          name: kustomize-enable-helm
      destination:
        server: '{{url}}'
        namespace: kube-system
