apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: harbor
  includeCRDs: true
  namespace: harbor
  releaseName: harbor
  version: 1.13.0
  repo: https://helm.goharbor.io
  valuesInline:
    externalURL: https://argocd.example.com
    expose:
      type: ingress
      tls: 
        certSource: auto
      ingress: 
        hosts: 
          core: argocd.example.com
    persistence:
      imageChartStorage:
        type: s3
        disableredirect: true
        s3: 
          region: ap-southeast-1
          bucket: window-server-2016
          existingSecret: mysecret
          #accesskey: AKIA6AXFC6HSEKC5VTG4
          #secretkey: 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
    registry:
      serviceAccountName: default
# - name: grafana
#   includeCRDs: true
#   namespace: default
#   releaseName: grafana
#   version: 6.59.0
#   repo: https://grafana.github.io/helm-charts