apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: harbor
  includeCRDs: true
  namespace: harbor
  releaseName: harbor
  version: 1.13.0
  repo: https://helm.goharbor.io
  valuesInline:
    replicas: 2
    externalURL: argocd.example.com
# - name: grafana
#   includeCRDs: true
#   namespace: default
#   releaseName: grafana
#   version: 6.59.0
#   repo: https://grafana.github.io/helm-charts